name: Test Against Regression
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: docker.mirror.hashicorp.services/hashicorp/jsii-terraform
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: ensure correct user
        run: chown -R root /__w/cdktf-integration-serverless-example/
      - name: Install Dependencies
        run: yarn 
      - name: Generate Provider Bindings
        run: yarn get
      - name: Test
        run: yarn test
      - name: Comment on failure
        if: ${{ failure() && github.event.pull_request }}
        env:
          PR_ID: ${{ github.event.pull_request.number }}
          GIT_BRANCH: ${{ github.event.pull_request.head.ref }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr comment $PR_ID --body "This test failure could mean that the snapshots need to be regenerated. Run \`git checkout $GIT_BRANCH\` followed by \`yarn test -- --passWithNoTests --updateSnapshot\`, and commit & push the results."
